version: "3.8"
services:
  mysql-server:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Manila
    ports:
      - 3308:3306
    restart: unless-stopped
    volumes: [db:/var/lib/mysql]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on: [mysql-server]
    ports:
      - 5000:80

  web:
    build:
      args:
        PHP_MODE: ${PHP_MODE}
      context: .
    depends_on: [mysql-server]
    ports:
      - 3000:80
    restart: unless-stopped
    volumes: [./:/var/www/html]

volumes:
  db: